### ISSUE TITLE
Not workin in my game

### ISSUE THREAD

**Issue by tavin44** [CptMoore/MechEngineer#103]
I downloaded this and dynalib and component file..put all 3 into Battletech/mods..and i start a new campaign and its not workin tried 3 new games..i then installed the new roguetech which has this in it and it works for that..but they changed certain files so i want the base mechengineer..any idea why main files not workin ?

**Comment by CptMoore** [comment]
hmm what exactly doesnt work? it works for me, can you try the MechEngineerWorkspace.zip release?

**Comment by tavin44** [comment]
yea ill try that i downloaded the MechEngineer-masterfile one

**Comment by tavin44** [comment]
Thx for telling me about the workspaxe zip ..its working fine now..i used the zip abouve it first time and that didnt work.

**Comment by CptMoore** [comment]
can you still tell me what exactly didnt work? engines just missing?
