### ISSUE TITLE
add real cockpits

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#11]
we need 3 head slots

small cockpits would use 1 but have neg effects
standard cockpits take 2 slots, that leaves one head slot empty

move existing cockpit upgrades to actual cockpits that are standard size, leave them with a ++ modifier in the name

dont forget to add weight

can easily be done:
- expand head to 3
- introduce new cockpits
- require the mech to mount a cockpit or be invalid
- have different sizes and weights for cockpits (use json, no coding necessary)

unsure on how to do:
- visually extend the head slots to 3
- make cockpits have cool new gameplay effects that weren't possible before
  - like adding more ++ variants
  - add more gameplay effects (e.g. crit. cockpit does no protection and gives aiming malus, cockpit with autopunchout support, small cockpits are cramped and mech warrior doesnt want to sprint at full speed in such a cockpit etc..)

> ShutdownCausesInjury

Reuse that code to implement Overheat causes

wait for #64 to be implemented, then add new stat OverheatCausesInjury

see Mech.CheckForHeatDamage on where to patch
see MechShutdownSequence.CheckForHeatDamage on injury code

**Comment by CptMoore** [comment]
I'd wait with adding real cockpits until we have enough of a gameplay change to warrant violating #3 . additionally, having a UI mod that expands the head slot count visually to 3 would be nice before doing this.

**Comment by CptMoore** [comment]
small cockpits were introduced in the future, unless we make a TT mod placed in the future, makes no sense to add them

**Comment by CptMoore** [comment]
For the small cockpit in the exotics package we need to enlarged the head slots.

Here some ideas for critical hits:
+1 to hit chance for ANY ranged weapon attack (sensor damage)
+1 injury to the pilot (unable to be countered) (cockpit / life support damage)
-50 to visual range (sensor damage)
-50 to sensor range (sensor damage)

**Comment by Aliencreature** [comment]
I think cockpit damage and life support damage should work differently.

Cockpit damage --> +1 injury
Life support destroyed --> +1 injury PER TURN

Since this is reopened, I would like to toss out the idea of supporting torso cockpits. They weigh 4 tons and have various penalties, but they can survive a head destruction.

**Comment by Aliencreature** [comment]
> I wouldnt do that, thats basically game over that cant be helped. However if life systems are crit or you are in a small cockpit, overheating a mech should hurt your mechwarrior.

You are right, actually, I looked it up in the TechManual:

>**Life Support (Head)**
Any critical hit knocks out this system permanently and
leaves the pilot vulnerable to increased heat; the other critical
location can still take damage, but this has no additional
effect. The MechWarrior takes 1 point of damage every Heat Phase
that the ’Mech’s internal heat ranges from 15–25, and 2 points
of damage for every turn that its internal heat is 26+ on the
Heat Scale.

So to translate this into Battletech game terms, +1 damage for every turn overheated, +2 on shutdown?

**Comment by CptMoore** [comment]
> ShutdownCausesInjury

Reuse that code to implement Overheat causes

**Comment by CptMoore** [comment]
RT did some stuff in the direction, should backport this to here

**Comment by CptMoore** [comment]
since its already done in RT, we can close this
