### ISSUE TITLE
Requesting Permissions

### ISSUE THREAD

**Issue by BlueStryker** [CptMoore/MechEngineer#114]
Hello CptMoore,

Thanks again for directing me to your mods; I love what you've been doing. As of now, your mod is incompatible with mine, and I was wondering if I could have your permission to use, and make adjustments to, your mods so that I can incorporate them directly into my own? As with the other CBT mods I'm now including you will receive credit for the work you've done. Thank you for your time and consideration.

**Comment by CptMoore** [comment]
Sure go ahead, if you need help with issues you encounter or improvement suggestion, dont hesitate to create new issues here or contact me on the MechEngineer discord server. RogueTech/LadyAlekto is the main user of the mod, you could probably copy configs or ideas from there and ask here for some support  Also, I havent balanced any costs and component availability for campaign play, so those aspects are still in need of work.

**Comment by BlueStryker** [comment]
Thank you! I will reach out if I need any help or if I think of anything that can improve the mod. :)
