### ISSUE TITLE
Some XL/LT engine weights are incorrect

### ISSUE THREAD

**Issue by adammartinez271828** [CptMoore/MechEngineer#116]
Some XL/LT engines have incorrect weights in the mechlab, i.e:

* LT180 weighs 5 tons, should weight 5.5.
* LT240 weighs 8.5 tons, should weigh 9.
* XL250 weighs 6 tons, should weigh 6.5.

etc.  There are lots more, all underweighted by half a ton.

This is caused by the utility doing round-to-even instead of traditional 1/2 round up that you would normally see.  Battletech always rounds up in these cases, so the round-to-even is breaking things.

Below is a screenshot from in-game, and a chopped segment from the Battletech tech manual, Master Engine Table:
![image](https://user-images.githubusercontent.com/3824752/44623873-32cc7680-a8a9-11e8-8bb1-ad09acc03d12.png)
![image](https://user-images.githubusercontent.com/3824752/44623865-00227e00-a8a9-11e8-90e2-e58eb37bd22a.png)

**Comment by CptMoore** [comment]
for xl etc.. we use fractional accounting rules. obviously Mathf.Round failed me. do you think roundup will be compatible with the whole table in regards to the engines?

Note that I use a script to calculate the gyro and use the table for the standard engine weights. there gyro is ceiled, so at least that sound correct? MechEngineer\engine_generator\generate.pl

**Comment by CptMoore** [comment]
so I added your round up
in regards to endo-steel and ff, there I just made it roundDown since I use it in a context of weight savings

**Comment by CptMoore** [comment]
I really dont like the jumpy-nature of the armor mods due to rounding, any suggestions to solve that?

**Comment by CptMoore** [comment]
think this was solved
