### ISSUE TITLE
Engine ratings 080-095 break everything

### ISSUE THREAD

**Issue by adammartinez271828** [CptMoore/MechEngineer#118]
If you use the generate.pl script to autogenerate json files for all the various engine ratings, the game will fail to load the mod correctly.

Specifically, the engine ratings 080, 085, 090, and 095 cause this effect.  The presence of any other engine rating json file doesn't seem to cause this issue.

**Comment by adammartinez271828** [comment]
It doesn't even appear to load it at all:

![image](https://user-images.githubusercontent.com/3824752/44630054-fc810c80-a925-11e8-9635-8ed46289c25a.png)

**Comment by CptMoore** [comment]
Oh, I think the numbers come with a leading zero and that messes things up. Probably some hex conversion going on. Will fix that.

**Comment by CptMoore** [comment]
fixed in 2f79b1a08ab4c148b5cd74c21f8f86293598a63d
