### ISSUE TITLE
Equipment weight scaled by chassis weight

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#123]
Lady:
> Equipment weight based on chassis tonnage which i scale through the structure factor right now

**Comment by CptMoore** [comment]
Lady
> Can you cut out the weight of the gyro from the core and make it a part of the item?
>
> So i can also scale it properly?

**Comment by LadyAlekto** [comment]
My thoughts exactly

I think something like 

"ComponentWeight": XX% (of chassis weight) 

"GyroFactor": 1 = takes the weight according to installed core (for default gyro)
"GyroFactor": 0.5 = for a XL gyro halves the default weight

**Comment by CptMoore** [comment]
I modified the feature to allow several items on the mech to use the same factor. factors are additive, so 1.1 and 1.2 means 1.3 in total. 0.8, 0.6 and 1.4 means 0.8 in total.
engine and gyro factors are now calculated per item like the rest of the weight calculations.
added a "ChassisFactor" to allow bonus descriptions based on chassis weight
