### ISSUE TITLE
gameplay balance + pricing + availability

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#13]
we just copy and paste rules from TT, but how well do they translate to the game mechanics?

# availability + pricing
## shops
* not all engines should be stock, only the bare minimum
* std but different engine ratings can only pop up on manufacturing worlds
* exotic engines can only pop up on other worlds (comp + light would be research worlds, xl would be former SLDF presence)

## salvage
* this would provide stock engine and what more?

## stock mechs
* SLDF mechs should come with state of the art stuff, endo-steel, xl engine, ferros-fibrous

**Comment by CptMoore** [comment]
@CrusherBob you have written before that you have worked on this, whats the status on this? need help? whats missing?

**Comment by CrusherBob** [comment]
Was planning to just make regular engines pretty readily available, ans wait for feedback from the mod users on things like:

How often do they lose engines?
(if they are using 'empty salvaged mech mod) how much trouble are they having getting engines to put in their mechs?
How much (extra) money are they making from selling salvaged engines?

-------------------

Then put up some optional shop files that also make XL and DHS readily available, and see what the general feedback on them is.

Standard would be that XL + DHS has some chance of showing up on star league presence worlds, and DHS also has a chance of showing up on black market worlds.

But think that would make them hard enough to get that there wouldn't be proper feedback about them.  Thus, the optional shop files.

**Comment by CptMoore** [comment]
I have added some shop files, but basically just added random stuff to them, if you can please fix those

**Comment by CptMoore** [comment]
from CrusherBob

> There's some game design theory about avoiding 'death spirals': where an 'early' loss means that you can't win the game, but if you don't know enough about the game, you don't know you passed the no win point some time ago. Xcom is sorta infamous for that; at least some work went into specifically avoiding that for Battletech, though. That's why, for example, new mechs and new guns seem relatively easy to get. If you almost never take internal damage and never really lose any guns, then you are swimming in replacements. But have seen at least some forum posts where people seem to be losing bits left and right.
> 
> That's part of why I wanted to look at how things like engine destruction on mechs, common-ness of available salvaged engines, and so one would actually work in the campaign before committing the making bog standard engines in shops 'rare'.
> 
> But for a real test, we need also some people to play who are much worse at the game. So my default idea was simply to make up to rating 200 or so engines available at any shop that sold an LRM10, and make the 201-400 rating engines available at shops at industrial worlds (or whatever the actual shop flag is) that sell LRM15s and 20s.
> 
> Then, if engines were common enough in the game after some playtesting, see about making them appear in the shop 'special' section, rather than the 'inventory' section. Of course, any rarer engine can be much rarer, as you don't need a special engine to drop your mechs in contracts.

> On engine pricing:
> In TT, bigger engines make mechs more expensive. But looking at the in game cost of mechs, the faster ones (with bigger engines) aren't really any more expensive that the slower mechs.
Example: a 50 ton 4/6 mech (centurion) is 2,692,000 for just the engine, chassis, etc; a 50 ton 5/8 mech (trebuchet) is 3,392,000
> 
> In the game, centurion A 4.2M | Centurion AL 4.3M | Trebuchet 4.6M
> 
> So my spitball answer to the cost of engines was to make std engines 500,000 C-Bills: expensive, but not likely to either break the bank if you had to buy them; nor likely to give you a lot of spare money if you had a lot of salvaged ones to sell.
> 
> Then Engines with DHS would cost 1.1M (in game each DHS is around 600,000 c-bills); but ~6.5M might actually be a better number.
> 
> I'm not sure what pricing to set for DHS in engine, since that's pretty much the biggest single upgrade possible for any mech. Of course, in TT it's quite cheap (around 100,000 C-bills).

**Comment by CptMoore** [comment]
@CrusherBob 

I made some changes to the costs of an engine, I used the CBT rules and assumed a 75 ton mech for all calculations.
https://github.com/CptMoore/MechEngineMod/blob/62e08ee16b31451ebdce8c711f6d15442eef0011/engine_generator/generate.sh#L30
That makes engine cost way too much for light mechs and a bit cheap for assault mechs. I also added a flag "autofixmechdefs" that auto-adds free engines to mechs when those are bought or rewarded from missions. Those are "cheap" in comparison as no additional costs are calculated.

A DHS conversion kit to convert and engine to DHS costs like 10 DHS.

**Comment by CptMoore** [comment]
I like everything you have written.

Additionally I would split rare stuff among factions if possible, based on what faction introduced a prototype first, e.g. compact by Free Worlds League, light by Lyran Commonwealth. (not really necessary, but a nice too to force the player to travel).

**Comment by CptMoore** [comment]
sounds good, you certainly know more about the lore than me

> Compact - Rare in Draconis, common if liked by Draconis (I think they and the Blakists used it first?)

yea you are right

**Comment by Aliencreature** [comment]
Found my Techmanual! Apparently Compact engines are Lyran as well, but they shared it with FedSuns and Draconis to help fight the Blakists.

**Comment by CptMoore** [comment]
So confusing, compact engines shouldnt help anyone 😂

**Comment by Aliencreature** [comment]
Supposedly they are more durable, but dying from engine crits compared to losing a CT must be so uncommon that they are pointless from a game perspective.

We *could* give them a bonus to justify the immense tonnage. XXL engines have a penalty to heat sinking because of their inadequate shielding, so Compacts could get a matching bonus to heat sinking instead. Alternatively, they could give a bonus to difficulty to hit because of their shielding, so they work well with ECM and/or stealth armor.

**Comment by CptMoore** [comment]
Bonus in heat dissipation makes sense, you pay more tonnage but get some back in form of heat sinks. Of course compact engines are required for that fat center torso cockpit right?

**Comment by Aliencreature** [comment]
No, the torso cockpit works like this according to Sarna:

>Torso Cockpits weigh 4 tons and replace the standard Cockpit. Torso Cockpits occupy two spaces in the Center Torso, one for the cockpit and one sensor package. The head mounted Life Support systems are moved to the side torsos. This leaves four critical slots open in the 'Mech's head. The cramped conditions impose a 1 point penalty on all Piloting skill rolls. When the first sensor system is destroyed, add a 2 point penalty on all to-hit rolls. After the second sensor system is destroyed, impose a 4 point to-hit penalty. (If the destroyed sensor systems are both in the head, the 'Mech is effectively blinded and the penalty applies to Piloting skill rolls and physical attacks as well.) If all three sensor systems are destroyed, the 'Mech is completely blind and cannot make weapon attacks as well as suffering a 4 point penalty to Piloting skill rolls.

>The proximity to the engine makes a MechWarrior's life difficult as well. The torso mounted life support systems are critical to the operation of the 'Mech. If one Life Support system is destroyed, the MechWarrior will take a point of damage each turn a Torso Cockpit equipped 'Mech is overheated by 1 to 14 points on the 'Mech heat scale. If the 'Mech is overheated by 15 points or more and a Life Support system is destroyed, the MechWarrior will take 2 points of damage.

But I suppose with a compact engine you could move the life support in the CT as well, making the mech very durable to anything but a CT destruction.

**Comment by CptMoore** [comment]
Ok, lets make a ticket for compact engine viability and another one for ct cockpits and movenour existing comments appropiatly.

**Comment by CptMoore** [comment]
I've implemented work order cost customization #85 , all installation and removal costs regarding engines, armor and structure can now be customized.

Additionally, costs can be made relative to chassis weight, e.g. Install TechCost = ChassisTonnage * 10.

we need someone to go through all components and set appropriate costs:
- costs to buy from store (and sell it)
- costs to install (relative to chassis tonnage if appropriate)
- costs to remove (relative to chassis tonnage if appropriate)

Don't forget that engines are more complicated, as we have several different parts that combined give the finished engine.

**Comment by CptMoore** [comment]
waiting for @LadyAlekto to finish this in RT so I can backport it here

**Comment by CptMoore** [comment]
this is just one of the backport tasks, no need to keep this open
