### ISSUE TITLE
add leg actuators

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#33]
legs:
  Hip
  Upper Leg
  Lower Leg
  Foot

arm:
  Shoulder
  Upper Arm (?)
  Lower Arm (optional)
  Hand (optional)

http://www.ci-n.com/~jcampbel/rpgs/battletech/FASA/3025/CPLT-C1-Catapult-stats.html
http://www.ci-n.com/~jcampbel/rpgs/battletech/FASA/3025/ON1-K-Orion-stats.html
http://www.ci-n.com/~jcampbel/rpgs/battletech/FASA/3025/GHR-5H-Grasshopper-stats.html

how does DFA upgrades work? -> what kind of actuator replacements? all 4?
how do the melee upgrades work? -> each chassis does supports different number of upgrades / actuators.

**Comment by Aliencreature** [comment]
So here's what I found in the TechManual for actuators.

**Arm Crits**
Shoulder: +4 to hit penalty on weapons mounted on the arm, mech may not punch with that arm (so +something difficulty to hit with melee?)
Upper Arm: +1 to hit penalty on weapons mounted on the arm, damage from punches halved + difficulty to hit with melee increased (probably translates to reduced melee damage in general)
Lower Arm: +1 to hit penalty on weapons mounted on the arm, damage from clubbing attacks halved + difficulty to hit with melee increased
Hand: only affects melee

**Leg Crits**
Hip: Piloting check for knock-down when crit, +2 to hit penalty for kick attacks and lower damage, reduced movement speed (to half), all piloting checks get +2 difficulty (and a piloting check every jump). **If the hip is crit, all other leg/foot crits for that leg are ignored and only the Hip crit is taken into account**. If a mech loses both hips its movement speed is reduced to 0, but it can still jump.
Upper Leg: Piloting check for knock-down when crit, +2 to hit penalty for kick attacks and lower damage, reduced movement speed (-1 MP in TT terms), all piloting checks get +1 difficulty (and a piloting check every jump)
Lower Leg: Piloting check for knock-down when crit, +1 to hit penalty for kick attacks and lower damage, reduced movement speed (-1 MP in TT terms), all piloting checks get +1 difficulty (and a piloting check every jump)
Foot: Piloting check for knock-down when crit, +1 to hit penalty for kick attacks, reduced movement speed (-1 MP in TT terms), all piloting checks get +1 difficulty (and a piloting check every jump)

**Comment by Grumpy-Au** [comment]
Personally, the leg actuators, while "nice", arn't all that important to the gameplay (and sound like a real pain to code into the game as a mod).

Returning the arm crit slots to 10 and adding lower arm and hand actuators (with relevant bonuses for arm weapons and melee) is something I'd like to see, and (at least with the melee component) far easier to work into the game.  Even if you retained the inbuilt bonuses for arm weapons the game currently has and just had the actuators affect melee (which can be done without any actual hard coding of .dll's)

**Comment by CptMoore** [comment]
```
"MeleePunchWeighting": 0.75,
"MeleeKickWeighting": 0.25,
"MeleeTackleWeighting": 0.1,
```

**Comment by CptMoore** [comment]
not done, closing for now since legs arent that important
