### ISSUE TITLE
Rename of the mod or split up

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#58]
Endo steel, armor, cockput, gyro, maybe more, nothing to do wiith engines.

We need a better name for it than MechEngineMod.

We could also split up stuff into different mods, but thatll reduce my coding time significantly due to overhead in switching between mods and copying code.

Current Candidates:
MechEngineer
MechInternals
Mechlab+
MechEngineer++!
MechTuneUps
PimpMyMech
MechEngineerRedux | KER
MechInternalRevamp | MIR
RealMechInsides  | RMI
MechR&D
MechWorkshop
MechPartsExpansion
MooreMechOptions
MechMoore 
MechTek

**Comment by Aliencreature** [comment]
Splitting the mods doesn't seem like the best idea. I'm all for making things with a single purpose, but the calculations seem just too intertwined to separate.

Rename it to something fancy like MechEngineer? MechInternals? Mechlab+?

**Comment by CptMoore** [comment]
Ohh i like MechEngineer alot

**Comment by CptMoore** [comment]
I asked the people on discord and the crowed came up with more names.
MechWorkshop is a nice contender to MechEngineer

**Comment by Aliencreature** [comment]
I like MechEngineer, MechWorkshop and Mech Internal Revamp for the cool acronym.

I'd also like to throw in MechTek in as a play on ModTek and the in-universe MechTechs that actually monkey around in the mechs and change all of these parts.

**Comment by CptMoore** [comment]
I think mech engineer > mech workshop. mech workshop actually finds mods on steam workshop to other games, thats very confusing. MIR is horribel to search for.

**Comment by Aliencreature** [comment]
Alright, MechEngineer then?
