### ISSUE TITLE
Torso Cockpits

### ISSUE THREAD

**Issue by Aliencreature** [CptMoore/MechEngineer#59]
**Sarna**

>Torso Cockpits weigh 4 tons and replace the standard Cockpit. Torso Cockpits occupy two spaces in the Center Torso, one for the cockpit and one sensor package. The head mounted Life Support systems are moved to the side torsos. This leaves four critical slots open in the 'Mech's head.[1] The cramped conditions impose a 1 point penalty on all Piloting skill rolls. When the first sensor system is destroyed, add a 2 point penalty on all to-hit rolls. After the second sensor system is destroyed, impose a 4 point to-hit penalty. (If the destroyed sensor systems are both in the head, the 'Mech is effectively blinded and the penalty applies to Piloting skill rolls and physical attacks as well.) If all three sensor systems are destroyed, the 'Mech is completely blind and cannot make weapon attacks as well as suffering a 4 point penalty to Piloting skill rolls.[2]

>The proximity to the engine makes a MechWarrior's life difficult as well. The torso mounted life support systems are critical to the operation of the 'Mech. If one Life Support system is destroyed, the MechWarrior will take a point of damage each turn a Torso Cockpit equipped 'Mech is overheated by 1 to 14 points on the 'Mech heat scale. If the 'Mech is overheated by 15 points or more and a Life Support system is destroyed, the MechWarrior will take 2 points of damage.[3]

**Comment by CptMoore** [comment]
Complicated due to hardcoded stuff in base game and even mods.

**Comment by CptMoore** [comment]
fast workaround
HeadShotImmunity: true

**Comment by CptMoore** [comment]
closing this for now, as low priority. tracking that this is in fact still open is done via TODO master list
