### ISSUE TITLE
Compact Engine Balance

### ISSUE THREAD

**Issue by Aliencreature** [CptMoore/MechEngineer#60]
Compact engines occupy only 3 slots in the CT but have +50% tonnage. Ideas to make the cost worth it:

1) Heat sinking bonus, either as a multiplier (+50% to all sinks?) or as free internal heat sinks.
2) Provide similar bonuses to stealth armor.
3) After the mechanics for reactive/reflective/etc. armor are implemented, use something similar to reduce damage taken to the CT structure.

**Comment by CptMoore** [comment]
Free absolute is better than percent based, since you never know how and when mutipliers are applied. Due to the rating split its hard to add absolute vales that scale (requires coding).

Using the same bonus of other components is meh.

**Comment by Aliencreature** [comment]
4) Make them act as free heat exchangers by reducing weapon heat
5) Make them act as free heat banks by increasing overheat threshold and max heat

**Comment by CptMoore** [comment]
I agree, I like 5. too! heat banks themselves are meh as extra items, but max heat stat increase makes sense if you get it for free on another item.

**Comment by Aliencreature** [comment]
For the cost of +50% engine tonnage, it should be a pretty significant bonus, and perhaps scaled with the engine rating so that high-grade Compact engines don't feel like a total waste of tonnage. Say... +(rating/400)% max heat, with the Compact 400 doubling the thresholds?

**Comment by CptMoore** [comment]
I would make it a flat increase, so I don't have to code something. 😁 compact engines are more useful on smaller mechs then. since low rating engines have fewer heat sinks, that extra increase in max heat is useful. larger mechs can be a bit slower and gain more space for additional heat sinks.

**Comment by CptMoore** [comment]
closing this, please reopen if worked on
