### ISSUE TITLE
TT-accurate XXL effects

### ISSUE THREAD

**Issue by Aliencreature** [CptMoore/MechEngineer#61]
>In game play, XXL fusion engines run hotter than their other fusion equivalents. Standing still (or expending no Thrust) generates 2 heat
points per turn, Walking/Safe Thrust movement generates 4 heat points, and Running/Max Thrust movement generates 6 heat points. Heat generated
by jumping is doubled for XXL engine users, costing 2 heat points per hex jumped, with a minimum of 6 points per jump.

**Comment by CptMoore** [comment]
Would be cool to know if json modding could do this.

**Comment by Aliencreature** [comment]
I am going to run some tests later, but so far here's what I *think* I can do with json:

1) Generate 6 heat (2x3)  on standing still.
2) Generate 12 heat (the 6 from 1 and +6) on movement.
3) Increase jump-jet heat.

What I don't think is possible with json is additional heat on running.

**Comment by Aliencreature** [comment]
I toyed around with it, and I can't do 2 or 3 either with only json edits. The functions that calculate walk, run and jump heat do not involve any values from this.statCollection.AddStatistic and ticks do not work as I expected. I am not skilled enough in Harmony to do this, but I think the solution is to add the following in InitStats():

```
this.statCollection.AddStatistic<int>("ExtraWalkHeat", 0);
this.statCollection.AddStatistic<int>("ExtraSprintHeat", 0);
this.statCollection.AddStatistic<int>("ExtraJumpHeatPerUnit", 0);
```

Then in public int WalkHeat:
```

public int WalkHeat
		{
			get
			{
				return (int)(((float)base.Combat.Constants.Heat.WalkHeat+(float)mech.StatCollection.GetValue<int>("ExtraWalkHeat")) * base.Combat.Constants.Heat.GlobalHeatIncreaseMultiplier);
			}
		}
```

Then in public int SprintHeat:

```

public int SprintHeat
		{
			get
			{
				return (int)(((float)base.Combat.Constants.Heat.SprintHeat+(float)mech.StatCollection.GetValue<int>("ExtraSprintHeat")) * base.Combat.Constants.Heat.GlobalHeatIncreaseMultiplier);
			}
		}
```

And in public int CalcJumpHeat change:

`int num2 = Mathf.Max(base.Combat.Constants.Heat.JumpHeatMin, num * base.Combat.Constants.Heat.JumpHeatPerUnit);
`

to

`int num2 = Mathf.Max(base.Combat.Constants.Heat.JumpHeatMin, num * (base.Combat.Constants.Heat.JumpHeatPerUnit+mech.StatCollection.GetValue<int>("ExtraJumpHeatPerUnit"));`

The code may not be exact, but after these are patched, walk, sprint and jump heat should be exposed for json modification.

**Comment by CptMoore** [comment]
Ill try you idea when im back from work, this would allow to avoid having too much hard coded. Would something like that be possible to define crit stages of an engine?

**Comment by Aliencreature** [comment]
I don't see why not! Unlike many of the game's other parts, the statCollection is not defined as an enum and thus can be modified by Harmony. Stats are very versatile from what I have seen because they can be accessed by pretty much everything, including item status effects.

**Comment by CptMoore** [comment]
Ive used statscollection to hold crit data before, but i never tried to add status effects to jsons and then interact with those effects in code via statscollection.

How would you define the jsons to contain different effects for different crit levels? (Additive, or not if possible)

**Comment by Aliencreature** [comment]
The way TT does it is:

Engine Crit 1 --> +5 heat/turn (which translates to +15 heat/turn in BT)
Engine Crit 2 --> +10 heat/turn (which translates to +30 heat/turn in BT)
Engine Crit 3 --> Shutdown/destruction

You would need to define new stats for each of the variables you want to expose to engine crits. So for the example of heat, you would define:

```
this.statCollection.AddStatistic<int>("EngineCrit1Heat", 0);
this.statCollection.AddStatistic<int>("EngineCrit2Heat", 0);
```

Then you use the functions you already have to check crit levels, and at crit level 1 you add EngineCrit1Heat to the mech's heat generation (or reduce its sinking by that much). You do the same for crit level 2.

In the engine CT's json, you add a status effect that would look like this:
```

    "statusEffects" : [
         {
            "durationData" : {
                "duration" : 1,
                "ticksOnActivations" : false,
                "useActivationsOfTarget" : false,
                "ticksOnEndOfRound" : false,
                "ticksOnMovements" : false,
                "stackLimit" : 1,
                "clearedWhenAttacked" : false
            },
            "targetingData" : {
                "effectTriggerType" : "Passive",
                "triggerLimit" : 1,
                "extendDurationOnTrigger" : 0,
                "specialRules" : "NotSet",
                "effectTargetType" : "Creator",
                "range" : 0,
                "forcePathRebuild" : false,
                "forceVisRebuild" : false,
                "showInTargetPreview" : false,
                "showInStatusPanel" : false
            },
            "effectType" : "StatisticEffect",
            "Description" : {
                "Id" : "StatusEffect-EngineCrit1Heat_STD",
                "Name" : "STD Crit #1 Heat",
                "Details" : "Generates an additional 15 heat/turn",
                "Icon" : "uixSvgIcon_equipment_ThermalExchanger"
            },
            "nature" : "Debuff",
            "statisticData" : {
                "appliesEachTick" : false,
                "effectsPersistAfterDestruction" : false,
                "statName" : "EngineCrit1Heat",
                "operation" : "Int_Add",
                "modValue" : "15",
                "modType" : "System.Int32",
                "additionalRules" : "NotSet",
                "targetCollection" : "NotSet",
                "targetWeaponCategory" : "NotSet",
                "targetWeaponType" : "NotSet",
                "targetAmmoCategory" : "NotSet",
                "targetWeaponSubType" : "NotSet"
            },
            "tagData" : null,
            "floatieData" : null,
            "actorBurningData" : null,
            "vfxData" : null,
            "instantModData" : null,
            "poorlyMaintainedEffectData" : null
        },
         {
            "durationData" : {
                "duration" : 1,
                "ticksOnActivations" : false,
                "useActivationsOfTarget" : false,
                "ticksOnEndOfRound" : false,
                "ticksOnMovements" : false,
                "stackLimit" : 1,
                "clearedWhenAttacked" : false
            },
            "targetingData" : {
                "effectTriggerType" : "Passive",
                "triggerLimit" : 1,
                "extendDurationOnTrigger" : 0,
                "specialRules" : "NotSet",
                "effectTargetType" : "Creator",
                "range" : 0,
                "forcePathRebuild" : false,
                "forceVisRebuild" : false,
                "showInTargetPreview" : false,
                "showInStatusPanel" : false
            },
            "effectType" : "StatisticEffect",
            "Description" : {
                "Id" : "StatusEffect-EngineCrit2Heat_STD",
                "Name" : "STD Crit #2 Heat",
                "Details" : "Generates an additional 30 heat/turn",
                "Icon" : "uixSvgIcon_equipment_ThermalExchanger"
            },
            "nature" : "Debuff",
            "statisticData" : {
                "appliesEachTick" : false,
                "effectsPersistAfterDestruction" : false,
                "statName" : "EngineCrit2Heat",
                "operation" : "Int_Add",
                "modValue" : "30",
                "modType" : "System.Int32",
                "additionalRules" : "NotSet",
                "targetCollection" : "NotSet",
                "targetWeaponCategory" : "NotSet",
                "targetWeaponType" : "NotSet",
                "targetAmmoCategory" : "NotSet",
                "targetWeaponSubType" : "NotSet"
            },
            "tagData" : null,
            "floatieData" : null,
            "actorBurningData" : null,
            "vfxData" : null,
            "instantModData" : null,
            "poorlyMaintainedEffectData" : null
        },
],
```

The engine's json defines how much heat is produced on a crit in the first round of its deployment, but you still need Harmony to enforce it. It doesn't even have to be just about engines either. Lets say you want to make hits to the fusion core reduce the damage of energy weapons to 50%:
`
this.statCollection.AddStatistic<float>("FusionCoreCritDamageReduction", 0);`

I don't have access to DNSpy right now, so I can't tell you exactly where it is, but somewhere the game has a reference to another statistic about doing less damage with energy weapons. You plug in the new FusionCoreCritDamageReduction so whatever that function spits out as the final damage is multiplied by (1-FusionCoreCritDamageReduction) *if there is a critical hit to the fusion core*.

Then on the json for the fusion core you define:

```

    "statusEffects" : [
         {
            "durationData" : {
                "duration" : 1,
                "ticksOnActivations" : false,
                "useActivationsOfTarget" : false,
                "ticksOnEndOfRound" : false,
                "ticksOnMovements" : false,
                "stackLimit" : 1,
                "clearedWhenAttacked" : false
            },
            "targetingData" : {
                "effectTriggerType" : "Passive",
                "triggerLimit" : 1,
                "extendDurationOnTrigger" : 0,
                "specialRules" : "NotSet",
                "effectTargetType" : "Creator",
                "range" : 0,
                "forcePathRebuild" : false,
                "forceVisRebuild" : false,
                "showInTargetPreview" : false,
                "showInStatusPanel" : false
            },
            "effectType" : "StatisticEffect",
            "Description" : {
                "Id" : "StatusEffect-FusionCoreCritDamageReduction",
                "Name" : "Fusion Core Crit Damage Reduction",
                "Details" : "Reduces energy damage to 50%.",
                "Icon" : "uixSvgIcon_equipment_ThermalExchanger"
            },
            "nature" : "Debuff",
            "statisticData" : {
                "appliesEachTick" : false,
                "effectsPersistAfterDestruction" : false,
                "statName" : "FusionCoreCritDamageReduction",
                "operation" : "Float_Add",
                "modValue" : "0.5",
                "modType" : "System.Int32",
                "additionalRules" : "NotSet",
                "targetCollection" : "NotSet",
                "targetWeaponCategory" : "NotSet",
                "targetWeaponType" : "NotSet",
                "targetAmmoCategory" : "NotSet",
                "targetWeaponSubType" : "NotSet"
            },
            "tagData" : null,
            "floatieData" : null,
            "actorBurningData" : null,
            "vfxData" : null,
            "instantModData" : null,
            "poorlyMaintainedEffectData" : null
        },
],
```

The code may not be exact, since I can't test any of it right now, but the gist of it is that you expose the variables you want to change through Harmony as statistics and then you define their values in the jsons for the equipment. On the above example, you could introduce reinforced fusion cores that only have -25% energy damage on a crit with *only* json modifications, or make compact engines generate only 10 heat/turn on a single crit. And you can even have equipment interact with them, say, a torso upgrade called 'Emergency Capacitors' that reduces FusionCoreCritDamageReduction by 0.25 or an 'Auxiliary Coolant Loop' that reduces the heat/turn on an engine crit.

And the best part? You can also make durable equipment like this, like armored versions of actuators whose CritLevel1 effects are 0 and CritLevel2 are the CritLevel1 of the ordinary ones. You can make compact engines shrug off the first critical hit. If it works, it will make it much easier to add more upgrades.

**Comment by CptMoore** [comment]
ok, I'll try to recap.

json defines MyCrit1 Stat
code consumes MyCrit1 on crit detection and applies its effects

I think we can do better

effectTriggerType OnHit
only used for weapons (meaning this setting is ignored everywhere I believe)
can be used to denote critical hits of components other than weapons

now statName can be the original stat you want to modify, e.g. CurrentHeat
that is crucial to the idea of status effects (they dont invent new stats)

issue left is how to define different effects on different crit levels, or how many crit levels are supported by a component. triggerLimit could be used to denote what status effect is active at what crit level. so you could skip a critical or have 2 status effects for the same critical level. triggerLimit = 1 is the first crit, 2 = second etc..

the maximum trigger limit also tells the game if the component is finally destroyed on a hit.

for the documentation

how to create an effect
```
if (effectData.targetingData.effectTriggerType == EffectTriggerType.Passive)
{
	string text = string.Format("PassiveEffect_{0}_{1}", this.parent.GUID, this.uid);
	this.combat.EffectManager.CreateEffect(effectData, text, -1, this.parent, this.parent, default(WeaponHitInfo), 0, false);
	this.createdEffectIDs.Add(text);
}
```

how to end an effect
```
List<Effect> allEffectsWithID = this.combat.EffectManager.GetAllEffectsWithID(this.createdEffectIDs[i]);
for (int j = 0; j < allEffectsWithID.Count; j++)
{
	if (allEffectsWithID[j].Target == this.parent)
	{
		this.parent.CancelEffect(allEffectsWithID[j], false);
	}
}
```

**Comment by Aliencreature** [comment]
This seems much cleaner. So if I am getting this right, any components that support these critical hit mechanics have a statuseffect entry in their JSON for each crit effect, which is defined by effectTriggerType = OnHit and triggerLimit = x, where x is the number of crits before it is triggered. 

The effect would be called once when its crit level is hit, or would it continue to be called for as long as the component is at the required crit level?

**Comment by CptMoore** [comment]
called once onHit. the effect will also be cancelled onhit, so if you have a status effect for crit 1 you want to keep for crit 2 you have to copy paste the status effect.

note this is very advanced, I think something to be done after release of a first version.

**Comment by Aliencreature** [comment]
Yup, and the posts after my proposed change to expose the walk/run/jump heat to JSON editing belong in a separate issue too. As soon as these are in and I test them the matter of XXL heat should be resolved.

**Comment by CptMoore** [comment]
agreed, can you edit and delete posts of others? or can only I do that?

**Comment by Aliencreature** [comment]
I can. Not sure if I can move them though, unless there's a way to split the topic.

**Comment by CptMoore** [comment]
didn't find any option to move either, have to copy/paste and use quote :(

**Comment by CptMoore** [comment]
moved out crit handling to #64

**Comment by CptMoore** [comment]
closing this, please reopen if worked on
