### ISSUE TITLE
TODO Components Master Table

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#71]
We need an overview to know what to work on next
this mod always had these priorities:
1. be CBT compatible (if you have to choose between CBT and gameplay, use a settings flag, otherwise CBT wins)
2. be lore compatible (basic package = game timeline, exotics = all timelines)
3. avoid boredom and uselessness (compact engine, I'm looking at you)

I therefore propose a table where we can see:
- component type and specifics (e.g. cockpit, head variants) (if a component requires a totally new effect that is hard to implement -> thats probably a new component type)
- in what package to put them
- shortlist of effects
- link to issues that will implement effects and any limitations for component type

thoughts?

examples:

component type | exotic | implemented effects | open issues
--- | --- | --- | ---
cockpits | -| life system, slots, death reason | #11
small cockpit | yes | see cockpits | ? needs more head slots
cockpits, torso| yes | see cockpits | #59
gyro | - | stability | CBT crits
XL gyro | yes | stability | CBT crits
Compact gyro | yes | stability | CBT crits
Heavy Duty gyro | yes | stability, crit resistance | CBT crits
engine | - | rating, tonnage, jj, speed, CBT crits | campaign balance #66 #13
xl engine | - | slot requirements | make them upgrades #52
light engine | yes | slot requirements | can mechs with LFEs survive side torso destruction? needs testing
other engines incl. clan | yes | slot requirements | make them upgrades #52 #60 
hardened armor | yes | 2x damage/point of armor, -mobility | #45 
reflective armor  | yes | half damage from energy weapons, 2x damage from melee | #45 
reactive armor  | yes | half damage from missiles, artillery/explosions (it exists in some campaign missions), chance to strip armor on hit| #45 
ferro-lamellor armor | yes | reduces all damage by 5 points/25 damage | #45
stealth armor | yes | difficulty to hit bonus, sensor bonus, +30 heat/turn when active | needs activator, slot requirements (needs ECM like how XLs need XL side torsos)
composite structure | yes | occupies no slots, reduces structure weight to 50% like endo, doubles damage taken to internal structure | #45 
reinforced structure | yes | occupies no slots, doubles structure weight, reduces damage to structure by half and reduces the chances of a critical hit on the unit | #45
Triple Strength Myomer  | yes | +melee dmg and +movmenet on heat | #68 #64 
MASC | yes | run = 2x walk speed on turn of activation | needs activator, ideally as an ability + needs way to roll 2D6 and deliver critical hits to both legs on a 2 + slot requirements (mutually exclusive with TSM, slots and tonnage as % of mech tonnage but placed as single component)

**Comment by Aliencreature** [comment]
I have the TechManual, Total Warfare and Tactical+Strategic Operations, so I can sit down and expand the table you already made with tech from there.

**Comment by CptMoore** [comment]
We should only add to the table if we actually start with adding them to the mod (have an issue or said item). Otherwise the table would get huge no?

Btw side torso destruction -> slotcount = number of crits. Light side destruction = 2 crits. Thats how I tried to implemen it.

**Comment by Aliencreature** [comment]
So far I have added only half-implemented techs or techs we have discussed already, and MASC, because the problems with its implementation are almost identical to those of stealth armor.

>Btw side torso destruction -> slotcount = number of crits. Light side destruction = 2 crits. Thats how I tried to implemen it.

Yup, that's how Tabletop does it if I recall. I can't test anything today, but I will confirm it tomorrow and mark LFEs done after.

**Comment by CptMoore** [comment]
We should have a copy of this table with only done stuff in the readme #57

**Comment by CptMoore** [comment]
btw @Aliencreature assign any tickets to yourself if you are working on it or planning to

**Comment by Denadan** [comment]
two levels
1. CBT ERA for replace of basic/exotics(cbt rules already have accessibility level of each item for given era)
- campaign is 3025 - pre 4th succession war, basic components and very rare lostek
- other example 3037-3048 - post 4th sw and before clan invasion, helm core retrieved, states begin to reinvent some of lostek, comstar lost some influence - so lostek(like is-pulse lasers) is avaliable, but advanced(x/er-pulse) or clan(clan-pulse) components - not.

2. cbt extension  - it is campaign +++ items. i like idea of it.

**Comment by CptMoore** [comment]
they (Alien + Lady) were talking about using tagging to introduce stuff by year in the store and salvage. there is apparently a mod out there that allows some form of it.

**Comment by CptMoore** [comment]
RT is probably already going to have everything anyway, might only need the table in the readme to know whats already implemented / backported

**Comment by CptMoore** [comment]
yep, closing this too, just need to look into RT when backporting
