### ISSUE TITLE
improve code quality by introduing reusablilty

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#73]
right now I have lots of features copy pasted, introduce a form of at least composition to share code:
- ValidateAdd - to only allow one item of a certain type
- Adjust*Upgrade - based on some parameters, change the item to something else (size or tonnage based)
- ValidationRulesCheck - make the mech invalid if something is missing
- Add*IfPossible - add something that isn't there with a default component

also would like some interfaces for even none-code clones stuff like
- ValidationRulesCheck
- AdjustTooltip
- etc..
that requires moving away from static method and start using instantiated singletons
(that would allow refactoring tools to work properly)

also go through methods and make sure they only reference what they need. Originally I wanted to make the patches small, so I put the resolution code inside the business logic. Now I probably want some adapters in between.
Patch -> Adapter -> Core business logic 

The business logic should be bound as methods to the core objects. Since C# supports extension methods, as long as no new state is concerns, one can keep those methods in separate classes as before.

I should probably do #65 before or as a first step.

**Comment by Denadan** [comment]
>ValidateAdd - to only allow one item of a certain type
https://www.youtube.com/watch?v=pSCgEn9gk8I
testing. this allow add items to unique list by it prefix and custom category.
auto replace item with same category when droped on widget.

valudation check still dont implemented.

i do this for armor but generalize for all items. add engines, shieldings and sidetorso parts - and it works.
but need to remove validationadd checks from engine, cose it interfire with this when you have enough slots to put item(for example if remove llaser from ct, it cancel core change with message "Core already installed")

settings and extentions
https://github.com/Denadan/MechEngineer/blob/master/source/UniqueItemStuff.cs
replacement
https://github.com/Denadan/MechEngineer/blob/master/source/Misc/UniqueController.cs

**Comment by CptMoore** [comment]
hey Denadan, thanks for those examples. I'll use them good to come up with something that works all items even the internals and all exotics.

**Comment by Denadan** [comment]
![default](https://user-images.githubusercontent.com/741313/42054921-5a632ada-7b1e-11e8-9ba4-1c1df315250c.png)
all "missed componentd" checks done by one uniquecontroller. only component related stuff left in its validation check
and validation checks done, changes commited

**Comment by CptMoore** [comment]
This is awesome. If you can make sure it works with existing save games that dont have the patch, existing that do, new save games, data in mechdefs in statcollections (campaign), skirmish settings saves, etc.. 
Only issue i see is maintainability, if this requires too much code to maintain, it will hurt more than we get out of it.
Anyway, if you are successful, you should make a lib out of it other mods can profit from it.

**Comment by CptMoore** [comment]
Now I use composition to select what functionality is resused. Except for some special handling as part of the engine, where there is lots none-sharable code, it should now be fairly clear what code has similar / shared logic. I also added a layer of "Handlers" that implement interfaces that either directly implement the interface or delegate to reusable "helper" classes.
