### ISSUE TITLE
remove endo-steel and ferros-fibrous from basic package

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#80]
since @Denadan is going to introduce a new slots mechanic, we shouldn't include those items in the base game as we will redo everything anyway.

@Aliencreature 

toughts?

**Comment by Aliencreature** [comment]
Just got home, so I am still catching up on all of this progress!

I think the basic package should include everything that is needed for all the stock mechs to make sense, including the SLDF ones. Can they be done without XL engines, endo or ferro?

**Comment by CptMoore** [comment]
in order to get ATLAS II running I was using endo-steel and an xl engine. can you play around?

**Comment by Aliencreature** [comment]
I'll take a look, but generally, I think endo and ferro should stay but without being integrated in stores. That way they exist for the SLDF mechs that need them, like the Atlas II, but they remain LosTech that you can't just buy.

**Comment by CptMoore** [comment]
@Denadan is currently trying to fit dynamic slots into the mod, we'll just wait until then #79
