### ISSUE TITLE
MechLab QoL improvements

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#84]
- ✔️ auto-install/uninstall linked items (XL Left/Right side torso)
- ✔️ auto-install default items (actuators)
- ✔️special slots (reserved for certain items, e.g. armor or structure type selection)

currently developed in CustomComponents

**Comment by CptMoore** [comment]
we already have an actuator ticket #33, one could already implement actuators, but they would be a pain to manage. so we need QoL features first

**Comment by Denadan** [comment]
1. done(+ autorepair)
2. done(include strip equip, repair and ready/assemble mech)
3. not directly. using category and default allowed locations special behaviour can be implemented 
like "1 per location, auto replace, min 1 equiped" + allowed location = ct. so it must be one item of this type in ct to save/use mech and it auto replace each one when you try put it on same location.

**Comment by CptMoore** [comment]
QoL is done, thx Denadan
