### ISSUE TITLE
heatsinks for smaller engines

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#90]
apparently all mechs get 10 free heat sinks and apparently people use ratings lower than 250

* redo tonnage calculations, remove up to 10 heatsink tonnages from the whole mech

Dont forget autofix, have to count heatsinks and remove those tonnages before fitting in an engine.

**Comment by GentlemanReaper** [comment]
Remove up to 8 heatsink tonnages, the minimum internal heatsinks a mech can have is 2, as in the case of the Urbanmech's 60 rated engine.
