### ISSUE TITLE
Make CBT-style crit system

### ISSUE THREAD

**Issue by GentlemanReaper** [CptMoore/MechEngineer#92]
With the engine and gyro critical hit effects in place, it's important to have a critical hit system in place to best take advantage of them. Vanilla critical hits happen far too infrequently to allow an engine or gyro destruction before the mech is destroyed, which affects the balance of the larger and smaller engine and gyro variants.

To start with:

- Add CBT-based hit chances (each weapon hit on structure has an 18% chance to deal 1 crit, 18% for 2 crits, 9% chance for 3 crits).

- LRMs roll crit chances for every 5 missiles (since BT doesn't have missile clustering like in CBT).

Things to consider:

- In CBT a 3 crit roll to the arms, legs and head will instantly destroy it, can/should this be implemented?

- This will have a substantial impact on economy, since equipment will be destroyed far more frequently.

**Comment by CptMoore** [comment]
Die Roll (2D6)    Effect
2-7                         No Critical Hit
8-9                         Roll 1 Critical Hit Location
10-11                       Roll 2 Critical Hit Locations
12                            Head/Limb Blown Off/Roll 3 Critical Hit Locations*

**Comment by CptMoore** [comment]
`GetCritChance`
```
GetCritMultiplier * Max(GetBaseCritChance, this.combat.Constants.ResolutionConstants.MinCritChance);
```

`GetBaseCritChance`
```
1f - GetCurrentStructure / GetMaxStructure
```

`GetCritMultiplier`
```
GetWeaponMultiplier * GetTargetEffectMutliplier
```

**Comment by CptMoore** [comment]
is a bit more complicated than anticipated, while writing my own crit system would be possible, maintaining it isnt. have to wait for someone else to implement it.

see AIM https://github.com/Sheep-y/Attack-Improvement-Mod/issues/9
