### ISSUE TITLE
custom ammo for different weapons

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#95]
Gentleman Reaper:
> Has anyone discovered a way or is becoming close to creating new ammo defs for new weapons?

CptMoore:
> i think with CC one can already configure dependencies on mount but not during gameplay
> so one could require special ammo to be mounted but during gameplay every weapon using the same ammo will use it up

```
        public void SetAmmoBoxes(List<AmmunitionBox> ammoBoxes)
        {
            List<AmmunitionBox> list = new List<AmmunitionBox>();
            foreach (AmmunitionBox ammunitionBox in ammoBoxes)
            {
                if (ammunitionBox.ammoCategory == this.AmmoCategory)
                {
                    list.Add(ammunitionBox);
                }
            }
            this.ammoBoxes = list;
        }
```

implement that somewhere in mod library, e.g. custom components or another minimod that depends on custom components. prototyp can be directly implemented in mechengineer to allow HGauss.

**Comment by CptMoore** [comment]
not done, while cool lets hope we might get a solution from HBS

**Comment by LadyAlekto** [comment]
1.4 we get it probably
